### ISSUE TITLE
Embedded copy of catch2 is too old and buggy

### ISSUE THREAD

**Issue by pgrt** [OmicsDataAutomation/TileDB#130]
Hello,

The code embeds a copy of catch2, but it lies several versions behind upstream which has solved some issues, e.g. https://github.com/catchorg/Catch2/issues/2421 which showed up for me when using the tip of master of your TileDB to build GenomicsDB.

In Debian unstable, linking to the Debian-packaged catch2 instead has solved this problem.

Cheers,
Pierre

**Comment by nalinigans** [comment]
`sudo apt-get catch2` or `catch2-devel` results in `E: Unable to locate package catch2`. I am going to build/install Catch2 explicitly from the main branch for now using :
```
git clone https://github.com/catchorg/Catch2.git
cd Catch2
cmake -Bbuild -H. -DBUILD_TESTING=OFF
sudo cmake --build build/ --target install
```
I am open to any suggestions. Thanks.

**Comment by pgrt** [comment]
Hello,

Thanks for considering; if you are on a Debian-based distribution I believe the catch2 package should be available in the repositories... but otherwise getting the package from the GitHub repo is also fine. I forgot to say I was using version 2.13.9:
    https://github.com/catchorg/Catch2/releases/tag/v2.13.9
as the tip of the master branch will one day be tagged 3.{something}, and (among others) the catch.hpp file has been removed at the tip.
Does grasping version 2.13.9 work for you?

Best wishes,
Pierre

**Comment by nalinigans** [comment]
I had moved to version 3.10 in this PR #131 as `brew install` on the Mac used this version. But, I can change it to v2.13.9 if necessary. Thanks.

**Comment by nalinigans** [comment]
Removed embedded copy of Catch2 Header and support versions 2 or 3 of Catch2. See #131.
